# Change these first
owner: TherapyBox # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Therapy Box website
    url: https://therapy-box.co.uk/
  - name: VocaQuest frontend staging
    url: http://frontend.staging.voca.therapy-box.co.uk/
  - name: VocaQuest server staging
    url: https://srv.staging.voca.therapy-box.co.uk/
  - name: VocaQuest frontend production
    url: https://app.voca-quest.com/
  - name: VocaQuest server production
    url: https://srv.voca-quest.com/
  - name: Predictable 5 API
    url: https://therapy-box.co.uk/pa_api.php
  - name: Chatable 5 API
    url: https://therapy-box.co.uk/ca_api.php
  - name: DCA play production
    url: https://play.languageexplorer.app/
  - name: DCA webplatform production
    url: https://web-platform.prod.voca.therapy-box.co.uk/
  - name: VERT web platform production
    url: https://vert-platform.prod.voca.therapy-box.co.uk/
  - name: Appnocrat
    url: https://www.appnocrat.com/
  - name: Jira
    url: https://jira.internal.therapy-box.co.uk/
  

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Therapy box apps uptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Upptime
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
